users:
  - username: admin
    password: admin123
  - username: test
    password: test123

api_token: "sk-1234567890abcdef"

menus:
  - id: welcome
    title: 主页
    url: /welcome.html
    icon: home
    default: true
  - id: page1
    title: 页面一
    url: /page1.html
    icon: file
  - id: page2
    title: 页面二
    url: /page2.html
  - id: offer_manage
    title: OFFER Manage
    children:
      - id: offer_create
        title: 创建 OFFER
        url: /offer/create.html
      - id: offer_list
        title: OFFER List
        url: /offer/list.html
      - id: offer_files
        title: 文件管理
        url: /offer/files.html
        icon: folder
