users:
  - username: admin
    password: admin123
  - username: test
    password: test123

menus:
  - id: welcome
    title: 主页
    url: /welcome
    default: true
  - id: page1
    title: 页面一
    url: /page1
  - id: page2
    title: 页面二
    url: /page2
  - id: offer_manage
    title: OFFER Manage
    children:
      - id: offer_create
        title: 创建 OFFER
        url: /offer/create
      - id: offer_list
        title: OFFER List
        url: /offer/list
